version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10